### ISSUE TITLE
`gleam/regex` was removed from `gleam_stdlib`

### ISSUE THREAD

**Issue by M1N0RM1N3R** [MystPi/chomp#3]
I originally created [this issue](https://github.com/hayleigh-dot-dev/nibble/issues/22) in the original `nibble` repo, but since this fork is also affected, I may as well also file one here, as a courtesy.
As a further courtesy, here's the text of the original issue:
> This change prevents nibble from compiling.
Luckily, it's a simple fix: adding gleam_regexp to the dependencies and then importing/referencing gleam/regexp instead of gleam/regex in the source.

**Comment by MystPi** [comment]
Thanks, I'll publish the fix ASAP. ❤️
